// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNNQtoNAuOK7OknmFgf20Ia85TwtmbugU',
    appId: '1:777188366729:web:9dd9636eb57e08ed442958',
    messagingSenderId: '777188366729',
    projectId: 'vyavsaypro-database',
    authDomain: 'vyavsaypro-database.firebaseapp.com',
    storageBucket: 'vyavsaypro-database.firebasestorage.app',
    measurementId: 'G-9ZJYBZR4Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt8iSL9r9rlJtuXNL3K-xrfI6Z6X3o74w',
    appId: '1:777188366729:android:b8cde7be3ae8c0ed442958',
    messagingSenderId: '777188366729',
    projectId: 'vyavsaypro-database',
    storageBucket: 'vyavsaypro-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzBZKSBx_i00NStTmOxwciHFKxeMlrY9E',
    appId: '1:777188366729:ios:e1c5643a17970a91442958',
    messagingSenderId: '777188366729',
    projectId: 'vyavsaypro-database',
    storageBucket: 'vyavsaypro-database.firebasestorage.app',
    iosBundleId: 'com.example.vyavsaypro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzBZKSBx_i00NStTmOxwciHFKxeMlrY9E',
    appId: '1:777188366729:ios:e1c5643a17970a91442958',
    messagingSenderId: '777188366729',
    projectId: 'vyavsaypro-database',
    storageBucket: 'vyavsaypro-database.firebasestorage.app',
    iosBundleId: 'com.example.vyavsaypro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNNQtoNAuOK7OknmFgf20Ia85TwtmbugU',
    appId: '1:777188366729:web:b144f949d1cf86c3442958',
    messagingSenderId: '777188366729',
    projectId: 'vyavsaypro-database',
    authDomain: 'vyavsaypro-database.firebaseapp.com',
    storageBucket: 'vyavsaypro-database.firebasestorage.app',
    measurementId: 'G-M0ZY8EQBVL',
  );
}
